In [81]:
import pandas as pd
import numpy as np
import re  #re is regex

In [83]:
#importing data

df = pd.read_csv("C:/Users/Bomma/Downloads/Gen AI Materials/GenAI-Powered Intelligent Hiring Assistant using RAG/Resume.csv")

In [85]:
df.tail()

,ID,Resume_str,Resume_html,Category
2479,99416532,RANK: SGT/E-5 NON- COMMISSIONED OFFIC...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION
2480,24589765,"GOVERNMENT RELATIONS, COMMUNICATIONS ...","<div class=""fontsize fontface vmargins hmargin...",AVIATION
2481,31605080,GEEK SQUAD AGENT Professional...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION
2482,21190805,PROGRAM DIRECTOR / OFFICE MANAGER ...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION
2483,37473139,STOREKEEPER II Professional Sum...,"<div class=""fontsize fontface vmargins hmargin...",AVIATION

In [87]:
df.shape

(2484, 4)

In [89]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [91]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [93]:
df.duplicated().sum()

0

In [95]:
df.dtypes.value_counts()

object    3
int64     1
Name: count, dtype: int64

In [97]:
df.describe()

                 ID
count  2.484000e+03
mean   3.182616e+07
std    2.145735e+07
min    3.547447e+06
25%    1.754430e+07
50%    2.521031e+07
75%    3.611444e+07
max    9.980612e+07

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

In [101]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [103]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
FINANCE                   118
ADVOCATE                  118
ACCOUNTANT                118
ENGINEERING               118
CHEF                      118
AVIATION                  117
FITNESS                   117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [105]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [107]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [109]:
df.rename(columns = {"Resume_str":"resume_text","Category":"category"},inplace = True)

In [111]:
df.columns

Index(['ID', 'resume_text', 'Resume_html', 'category'], dtype='object')

In [113]:
#We create a reusable cleaning function
# \s ---> white spaces  \S ----> matches everything except the space

def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r'\S+@\S+', '', text)  # remove emails  #\b means start of the word and \b means end of the word
    text = re.sub(r'http\S+', '', text)  # remove URLs
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # remove special chars
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra spaces
    return text

In [115]:
#applying cleaning on resume_text column

df["cleaned_text"] = df["resume_text"].apply(clean_text)

In [117]:
#comparing before vs after we should not see any emails,symbols. only clean readable text should be
#\n ---> is for new line Original---> is just label to see output
#[500]-----> this is string slicing from 1st row to first 500 characters
#[i]---> helps to take one resume at a time without [i] we get all resumes
#[i]:[500]---> to first 500 characters of ith resume

for i in range(5):
    print(f"\n ---Resume{i}----")
    print("Original:\n",df["resume_text"][i][:500])
    print("\nCleaned:\n",df["cleaned_text"][i][:500])

 ---Resume0----
Original:
          HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task

Cleaned:
 hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multitasker client relations specialist accomplishments missouri d

 ---Resume1----
Original:
          HR SPECIALIST, US HR OPERATIONS       Summary     Versatile  media professional with background in Communications, Marketing, Human Resources and Technology.         Experience     09/2015   to   Current     HR Specialist, US HR Operations    Company Name   －   City  ,   State       Managed communication regarding launch of Operations group, policy changes and system outages      Designed standard work and job aids to create comprehensive training program for new employees and contracto

Cleaned:
 hr specialist us hr operations summary versatile media professional with background in communications marketing human resources and technology experience to current hr specialist us hr operations company name city state managed communication regarding launch of operations group policy changes and system outages designed standard work and job aids to create comprehensive training program for new employees and contractors audited job postings for old pending onhold and draft positions audited unio

 ---Resume2----
Original:
          HR DIRECTOR       Summary      Over 20 years experience in recruiting,   15 plus years in Human Resources Executive Management,   5 years of HRIS development and maintenance  4 years working in a Healthcare Enviroment        Skills          Recruiting  FMLA/EEO/FLSA   HRIS Development      Benefit Administration  Policy Development  Web Page Development             Accomplishments      Kansas Health Institute -Health Outcomes for the State of Kansas -1999
Memberships and Accolades: Pro

Cleaned:
 hr director summary over years experience in recruiting plus years in human resources executive management years of hris development and maintenance years working in a healthcare enviroment skills recruiting fmlaeeoflsa hris development benefit administration policy development web page development accomplishments kansas health institute health outcomes for the state of kansas memberships and accolades project management institute member shrm chamber of commerce friends university presidents hon

 ---Resume3----
Original:
          HR SPECIALIST       Summary    Dedicated, Driven, and Dynamic with over 20 years of customer service expertise. Motivated to maintain customer satisfaction and contribute to company success with an emphasis in personnel and process management. Solid team player with proven ability to establish rapport with clients.       Skills          Type 50 wpm and 10-Key by touch  Microsoft programs Word, Excel, Access, Outlook, PowerPoint  Personnel management  and Telephone inquiries specialist

Cleaned:
 hr specialist summary dedicated driven and dynamic with over years of customer service expertise motivated to maintain customer satisfaction and contribute to company success with an emphasis in personnel and process management solid team player with proven ability to establish rapport with clients skills type wpm and key by touch microsoft programs word excel access outlook powerpoint personnel management and telephone inquiries specialist excellent customer service skills with call quality and

 ---Resume4----
Original:
          HR MANAGER         Skill Highlights           HR SKILLS  HR Department Startup  Three New Organization Startups  Employment Law  FMLA/ADA/EEO/WC  Mediation & Advocacy  HR Policies & Procedures	*Staff Recruitment & Retention  Salary Negotiations  Employee Relations  Benefits Administration  Unemployment Administration  Worker's Compensation Administration  Orientation & On-Boarding  HRIS Technologies  Training & Development  Performance Management  Organizational Development  HR Program/

Cleaned:
 hr manager skill highlights hr skills hr department startup three new organization startups employment law fmlaadaeeowc mediation advocacy hr policies procedures staff recruitment retention salary negotiations employee relations benefits administration unemployment administration workers compensation administration orientation onboarding hris technologies training development performance management organizational development hr programproject management hris applications lawson paychex kronos ad

In [119]:
#saving cleaned data
#index = False because we dont want to create any wanted index column in the saved data

df.to_csv("cleaned_dataset.csv",index = False)

In [77]:
import sys
!{sys.executable} -m pip install nltk spacy
!{sys.executable} -m spacy download en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (3.9.1)
Collecting spacy
  Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl.metadata (28 kB)
Requirement already satisfied: click in c:\users\bomma\appdata\roaming\python\python312\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\bomma\appdata\roaming\python\python312\site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from nltk) (4.66.5)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Using cached murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Using cached cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Downloading weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Downloading confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from spacy) (0.24.1)
Requirement already satisfied: numpy>=1.19.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from spacy) (24.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.8.30)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Using cached blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm->nltk) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\programdata\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (13.7.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Downloading cloudpathlib-0.24.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: smart-open>=5.2.1 in c:\programdata\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in c:\programdata\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: anyio in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.2)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.2 MB 4.2 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/14.2 MB 3.3 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/14.2 MB 233.8 kB/s eta 0:00:56
   ----- ---------------------------------- 2.1/14.2 MB 390.2 kB/s eta 0:00:32
   -------- ------------------------------- 2.9/14.2 MB 530.9 kB/s eta 0:00:22
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 3.9/14.2 MB 709.6 kB/s eta 0:00:15
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ----------- ---------------------------- 4.2/14.2 MB 619.8 kB/s eta 0:00:17
   ------------ --------------------------- 4.5/14.2 MB 426.1 kB/s eta 0:00:23
   ------------- -------------------------- 4.7/14.2 MB 445.6 kB/s eta 0:00:22
   -------------- ------------------------- 5.0/14.2 MB 461.7 kB/s eta 0:00:21
   -------------- ------------------------- 5.2/14.2 MB 480.8 kB/s eta 0:00:19
   ---------------- ----------------------- 5.8/14.2 MB 516.6 kB/s eta 0:00:17
   ---------------- ----------------------- 6.0/14.2 MB 532.6 kB/s eta 0:00:16
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------ --------------------- 6.6/14.2 MB 566.3 kB/s eta 0:00:14
   ------------------- -------------------- 6.8/14.2 MB 536.3 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.2 MB 548.7 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.2 MB 548.7 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.2 MB 548.7 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.2 MB 548.7 kB/s eta 0:00:14
   ------------------- -------------------- 7.1/14.2 MB 548.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   -------------------- ------------------- 7.3/14.2 MB 526.7 kB/s eta 0:00:14
   --------------------- ------------------ 7.6/14.2 MB 397.8 kB/s eta 0:00:17
   ---------------------- ----------------- 7.9/14.2 MB 408.9 kB/s eta 0:00:16
   ----------------------- ---------------- 8.4/14.2 MB 430.5 kB/s eta 0:00:14
   ------------------------- -------------- 9.2/14.2 MB 467.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   -------------------------- ------------- 9.4/14.2 MB 478.2 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   --------------------------- ------------ 9.7/14.2 MB 444.1 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.0/14.2 MB 416.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.2/14.2 MB 395.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.2/14.2 MB 395.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.2/14.2 MB 395.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.2/14.2 MB 395.0 kB/s eta 0:00:11
   ---------------------------- ----------- 10.2/14.2 MB 395.0 kB/s eta 0:00:11
   ----------------------------- ---------- 10.5/14.2 MB 389.7 kB/s eta 0:00:10
   ------------------------------ --------- 10.7/14.2 MB 396.9 kB/s eta 0:00:09
   ------------------------------ --------- 10.7/14.2 MB 396.9 kB/s eta 0:00:09
   ------------------------------ --------- 10.7/14.2 MB 396.9 kB/s eta 0:00:09
   ------------------------------ --------- 10.7/14.2 MB 396.9 kB/s eta 0:00:09
   ------------------------------ --------- 10.7/14.2 MB 396.9 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------ --------- 11.0/14.2 MB 390.2 kB/s eta 0:00:09
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   ------------------------------- -------- 11.3/14.2 MB 371.7 kB/s eta 0:00:08
   --------------------------------- ------ 11.8/14.2 MB 372.6 kB/s eta 0:00:07
   ----------------------------------- ---- 12.6/14.2 MB 397.7 kB/s eta 0:00:05
   ---------------------------------------  14.2/14.2 MB 447.5 kB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 444.9 kB/s eta 0:00:00
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading confection-1.3.3-py3-none-any.whl (35 kB)
Using cached cymem-2.0.13-cp312-cp312-win_amd64.whl (40 kB)
Using cached murmurhash-1.0.15-cp312-cp312-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl (122 kB)
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl (652 kB)
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--

  WARNING: The script weasel.exe is installed in 'C:\Users\Bomma\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script spacy.exe is installed in 'C:\Users\Bomma\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Defaulting to user installation because normal site-packages is not writeable
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 4.2 MB/s eta 0:00:03
     ---- ----------------------------------- 1.3/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ---------------------------------- 1.6/12.8 MB 953.2 kB/s eta 0:00:12
     ------ --------------------------------- 2.1/12.8 MB 1.1 MB/s eta 0:00:10
     --------- ------------------------------ 2.9/12.8 MB 1.4 MB/s eta 0:00:08
     ----------- ---------------------------- 3.7/12.8 MB 1.6 MB/s eta 0:00:06
     ------------ --------------------------- 3.9/12.8 MB 1.7 MB/s eta 0:00:06
     -------------- ------------------------- 4.7/12.8 MB 1.8 MB/s eta 0:00:05
     ----------------- ---------------------- 5.5/12.8 MB 1.9 MB/s eta 0:00:04
     ------------------- -------------------- 6.3/12.8 MB 2.1 MB/s eta 0:00:04
     --------------------- ------------------ 6.8/12.8 MB 2.1 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.1 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.1 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.1 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.1 MB/s eta 0:00:03
     ---------------------- ----------------- 7.1/12.8 MB 1.6 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.8 MB 1.6 MB/s eta 0:00:04
     ---------------------- ----------------- 7.3/12.8 MB 1.6 MB/s eta 0:00:04
     ------------------------ --------------- 7.9/12.8 MB 1.6 MB/s eta 0:00:04
     --------------------------- ------------ 8.7/12.8 MB 1.7 MB/s eta 0:00:03
     ------------------------------ --------- 9.7/12.8 MB 1.8 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.8 MB 1.9 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 1.9 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 1.9 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 1.9 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [121]:
# NLP Processing

In [123]:
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [127]:
#downloading NLTK Data
#using this for tokenization,stopword removal,resume cleaning

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Bomma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Bomma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [129]:
#loading spacy model

nlp = spacy.load("en_core_web_sm")

In [131]:
#define stopwords

stop_words = set(stopwords.words('english'))

In [133]:
#advanced cleaning function

def advanced_cleaning(text):
    words = word_tokenize(text)  #tokenize means splitting text into individual words
    words = [word for word in words if word not in stop_words and len(word)>2]  # going through each word and removes common useless words and using 
    #len(word)>2 removes small words like a,an,it etcc....
    return " ".join(words)  #comibe back list to string 

#doing this to reduce noise ,keep meaningful words, impore ML model accuracy for our resume screening

In [137]:
#making a new column and applying the def function

df["Processed_text"] = df["cleaned_text"].apply(advanced_cleaning)

In [139]:
#lemmatization is done to convert a word to its base/root form (meaningful one)
#example : running ----> run, better ----> good, studies ---->study
# we are using lemmatization instead of stemming because its accuracy is high and used in NLP/ML models and also helps to reduce duplicate meaning
# and keeps meaningful words

def lemmatize_text(text):
    doc = nlp(text)  #storing NLP rich structured data in doc 
    return " ".join([token.lemma_ for token in doc])  #converts list to string
    
#token.lemma_
#Returns base form of word

In [ ]:
#spaCy:

#Tokenizes text
#Understands grammar
#Assigns lemma to each word

#we can see gramatically error but ML cares about meaning not grammar

#Avoid Lemmatization when:

#Grammar matters (like chat output)
# we are using this becuase developing,developer,developed etc.. in resume ------->develop using lemma

In [141]:
df["Lemmatized_text"] = df["Processed_text"].apply(lemmatize_text)

In [143]:
print("Cleaned:\n",df["cleaned_text"][0][:300])  #300 means limmiting to 300 characters
print("\nProcessed:\n",df["Processed_text"][0][:300])
print("\nLemmatized:\n",df["Lemmatized_text"][0][:300])


#helps to check how the text cleaning took place

Cleaned:
 hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highli

Processed:
 administratormarketing associate administrator summary dedicated customer service manager years experience hospitality customer service management respected builder leader customerfocused teams strives instill shared enthusiastic commitment customer service highlights focused customer satisfaction t

Lemmatized:
 administratormarkete associate administrator summary dedicated customer service manager year experience hospitality customer service management respect builder leader customerfocuse team strive instill share enthusiastic commitment customer service highlight focus customer satisfaction team manageme

In [145]:
def extract_keywords(text):
    doc = nlp(text)  #process texts using spacy
    keywords = [token.text for token in doc if token.pos_ in ['NOUN', 'PROPN']]   #token.text --->original word, token.pos---->parts of speech
    return keywords


#Keep only:

#NOUN → general important terms
#PROPN → specific names (skills, tools, companies)

#returns Output = list of important words

In [ ]:
#What is the goal of this function?

#👉 To keep only important words like:

#skills (Python, SQL)
#roles (Analyst, Engineer)
#tools (Tableau, Power BI)
#names (companies, technologies)

#👉 And remove less useful words like:

#is, the, was, very, etc.


#example
#text = "I am a Data Analyst skilled in Python and SQL at Google"

#output
#['Data', 'Analyst', 'Python', 'SQL', 'Google']



#helps is resume screening,feature engineering,job matching

In [147]:
df["Keywords"] = df["Lemmatized_text"].apply(extract_keywords)

In [149]:
df.to_csv("Final processed data.csv",index = False)

In [ ]:
#creating the JD's

In [151]:
job_descriptions = [
    {
        "role": "Data Analyst",
        "description": """
        Looking for a Data Analyst with strong skills in Python, SQL, Excel, and Power BI.
        Candidate should have experience in data visualization, data cleaning, and reporting.
        Knowledge of statistics and business insights is required.
        """
    },
    {
        "role": "Machine Learning Engineer",
        "description": """
        Seeking an ML Engineer with experience in Python, machine learning, deep learning, and NLP.
        Should be familiar with TensorFlow or PyTorch and model deployment.
        """
    },
    {
        "role": "HR Analyst",
        "description": """
        Looking for an HR Analyst with experience in recruitment analytics, employee data analysis,
        HR dashboards, and reporting. Knowledge of Excel and data visualization tools required.
        """
    },
    {
        "role": "Software Engineer",
        "description": """
        Seeking a Software Engineer skilled in Python, Java, APIs, and backend development.
        Experience with databases and system design is preferred.
        """
    },
    {
        "role": "Data Scientist",
        "description": """
        Looking for a Data Scientist with expertise in Python, machine learning, statistics,
        data analysis, and predictive modeling.
        """
    },
    {
        "role": "Business Analyst",
        "description": """
        Seeking a Business Analyst with strong analytical skills, stakeholder communication,
        data analysis, and reporting experience.
        """
    },
    {
        "role": "DevOps Engineer",
        "description": """
        Looking for a DevOps Engineer with experience in CI/CD pipelines, cloud platforms,
        Docker, Kubernetes, and automation tools.
        """
    },
    {
        "role": "Frontend Developer",
        "description": """
        Seeking a Frontend Developer skilled in HTML, CSS, JavaScript, React, and UI/UX design.
        """
    },
    {
        "role": "Backend Developer",
        "description": """
        Looking for a Backend Developer with experience in APIs, databases, Python, and system architecture.
        """
    },
    {
        "role": "AI Engineer",
        "description": """
        Seeking an AI Engineer with experience in NLP, LLMs, RAG systems, machine learning,
        and deep learning frameworks like PyTorch or TensorFlow.
        """
    }
]

In [155]:
#converting the JD to dataframe

jd_df = pd.DataFrame(job_descriptions)
jd_df.head(10)

,role,description
0,Data Analyst,\n Looking for a Data Analyst with stro...
1,Machine Learning Engineer,\n Seeking an ML Engineer with experien...
2,HR Analyst,\n Looking for an HR Analyst with exper...
3,Software Engineer,\n Seeking a Software Engineer skilled ...
4,Data Scientist,\n Looking for a Data Scientist with ex...
5,Business Analyst,\n Seeking a Business Analyst with stro...
6,DevOps Engineer,\n Looking for a DevOps Engineer with e...
7,Frontend Developer,\n Seeking a Frontend Developer skilled...
8,Backend Developer,\n Looking for a Backend Developer with...
9,AI Engineer,\n Seeking an AI Engineer with experien...

In [157]:
jd_df['cleaned_description'] = jd_df['description'].apply(clean_text)

In [159]:
jd_df['processed_description'] = jd_df['cleaned_description'].apply(advanced_cleaning)

In [165]:
jd_df["lemmatized_description"] = jd_df['processed_description'].apply(lemmatize_text)

In [169]:
#extracting keywords from JD's

jd_df['jd_keywords'] = jd_df['lemmatized_description'].apply(extract_keywords)

In [171]:
jd_df.to_csv("job_descriptions.csv",index = False)

In [173]:
print(jd_df[['role', 'jd_keywords']])

                        role  \
0               Data Analyst
1  Machine Learning Engineer
2                 HR Analyst
3          Software Engineer
4             Data Scientist
5           Business Analyst
6            DevOps Engineer
7         Frontend Developer
8          Backend Developer
9                AI Engineer

                                         jd_keywords
0  [datum, analyst, strong, skill, python, excel,...
1  [engineer, experience, python, machine, learni...
2  [analyst, experience, recruitment, employee, d...
3  [software, engineer, python, java, apis, backe...
4  [datum, scientist, expertise, python, machine,...
5  [business, analyst, skill, stakeholder, commun...
6  [engineer, experience, cicd, pipeline, cloud, ...
7  [frontend, developer, html, css, javascript, r...
8  [developer, experience, apis, database, python...
9  [engineer, experience, nlp, llms, rag, system,...

In [175]:
#now we are using sentence transformers ---> this converts text to numeric vectors(embeddings)
#TF-IDF misses the text meaning where as embeddings / sentence transformers captuers it 

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#Resume text → embedding
#Job description → embedding
#Compare using cosine similarity

In [177]:
#we are using this model as it is fast and helps in good semantic understanding and is a sentence embedding model
#converts sentences ---> numbers
#loading pretrained NLP model from hugging face model hub

model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [181]:
#creating resume embeddings 

resume_embeddings = model.encode(df["Lemmatized_text"].tolist(), show_progress_bar=True)

Batches:   0%|          | 0/78 [00:00<?, ?it/s]

In [183]:
#creating JD embeddings 
#.tolist() ---> converts pandas series  to python list
#SentenceTransformer.encode() expects: a list of sentences hence we used .tolist()


jd_embeddings = model.encode(jd_df['lemmatized_description'].tolist(), show_progress_bar=True)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [199]:
#checking similarity like matching JD with all resumes

all_similarity_scores = cosine_similarity(jd_embeddings, resume_embeddings)    #cosine similarity compares 1 JD with all resumes vectors
    #[jd_embeddings[0]],  # first JD , using two brackets becuase cosine similarity 2D array(matrix),not a single vector
    #resume_embeddings    #has all resume vectors
#)

In [ ]:
#for all JD's and all resume comparisons we just need to use 
#cosine_similarity(jd_embeddings, resume_embeddings)

In [201]:
#to get top candidates
#.argsort ---> to sort the array in ascending order 
#[-5:]-----> Takes last 5 indices (highest scores)
# [::-1] ----> reverse order


#.argsort() → gives rank order
#👉 [-5:] → top students
#👉 [::-1] → best first
# if we want top 10 then [-10:]
import numpy as np

# to get top candidates
top_indices = similarity_scores[0].argsort()[-5:][::-1]

In [203]:
#to display results to pick the best matching resume based on similarity scores

for idx in top_indices:    #loop through each index in top results and idx = position of a resume 
    print(f"Score: {similarity_scores[0][idx]:.2f}")  #to get similarity score of that resume
    print(f"Category: {df.iloc[idx]['category']}")  #df.iloc[idx]----->Gets the row at position idx, ["category"]----->tells which category resume fits
    print(f"Resume Preview: {df.iloc[idx]['resume_text'][:100]}")
    print("-" * 50) #prints a separator line

Score: 0.60
Category: DIGITAL-MEDIA
Resume Preview:          SENIOR DIGITAL MARKETING ANALYST       Summary    Highly analytical and process-oriented da
--------------------------------------------------
Score: 0.59
Category: ENGINEERING
Resume Preview:          ENGINEERING AND QUALITY TECHNICIAN       Career Overview    A highly experienced skilled gr
--------------------------------------------------
Score: 0.57
Category: AUTOMOBILE
Resume Preview:          DATA ANALYST       Professional Summary    Industrial and Systems Engineering graduate, cer
--------------------------------------------------
Score: 0.56
Category: CONSULTANT
Resume Preview:          CONSULTANT       Summary    College graduate with interest in insurance claims work. Proven
--------------------------------------------------
Score: 0.56
Category: CONSULTANT
Resume Preview:        Pavithra  Shetty           Summary     Customer-oriented Principal Consultant knowledgeable a
--------------------------------------------------

In [ ]:
#candidate Ranking model (ML Logic), we build multi factor ranking system

In [259]:
#role based skill dictionary 

role_skills = {
    "Data Analyst": {"python", "sql", "excel", "data", "analysis"},
    "Data Scientist": {"python", "machine", "learning", "model", "statistics"},
    "HR Analyst": {"hr", "recruitment", "employee", "analytics"},
}

In [261]:
#weighted skill matching score 

def skill_match_score(jd_keywords, resume_keywords, role):
    jd_set = set(jd_keywords)
    resume_set = set(resume_keywords)
    
    role_specific = role_skills.get(role, set())
    
    score = 0
    
    for word in jd_set:
        if word in resume_set:
            if word in role_specific:
                score += 3   # high importance
            else:
                score += 1
    
    return score / (3 * len(jd_set))

In [265]:
#experience score function

def experience_score(text):
    word_count = len(text.split())
    
    if word_count < 100:
        return 0.3
    elif word_count < 300:
        return 0.6
    else:
        return 1.0

In [263]:
#final score function

def final_score(similarity, skill_score, exp_score):
    return (
        0.4 * similarity +
        0.5 * skill_score +
        0.1 * exp_score
    )

In [277]:
#master function

def rank_candidates(jd_index, top_n=5):
    results = []
    
    role = jd_df.iloc[jd_index]['role']  # get role once
    
    for i in range(len(df)):
        
        # --- STEP 1: HARD FILTER (VERY IMPORTANT) ---
        if role == "Data Analyst":
            resume_keywords = df.iloc[i]['Keywords']

            # Require at least 2 strong skills
            required_skills = ["python", "sql", "analysis", "data"]
            
            match_count = sum(1 for skill in required_skills if skill in resume_keywords)
            
            if match_count < 2:
                continue

        
        if role == "HR Analyst":
            resume_keywords = df.iloc[i]['Keywords']

            required_skills = ["hr", "recruitment", "employee", "management"]

            match_count = sum(1 for skill in required_skills if skill in resume_keywords)

            if match_count < 2:
                continue
        
        # --- STEP 2: GET SCORES ---
        sim = all_similarity_scores[jd_index][i]
        
        skill = skill_match_score(
            jd_df.iloc[jd_index]['jd_keywords'],
            df.iloc[i]['Keywords'],
            role
        )
        
        # Optional filter (keep it)
        if skill < 0.2:
            continue
        
        exp = experience_score(df.iloc[i]['Lemmatized_text'])
        
        score = final_score(sim, skill, exp)
        
        results.append((i, score))
    
    # --- STEP 3: SORT ---
    results = sorted(results, key=lambda x: x[1], reverse=True)
    
    # --- STEP 4: PRINT ---
    print(f"\nTop {top_n} candidates for role: {role}\n")
    
    for idx, score in results[:top_n]:
        print("Final Score:", round(score, 3))
        print("Category:", df.iloc[idx]['category'])
        print("Preview:", df.iloc[idx]['resume_text'][:150])
        print("-" * 60)
    
    return results

In [279]:
#running for data analyst 

rank_candidates(jd_index=0, top_n=5)

Top 5 candidates for role: Data Analyst

Final Score: 0.458
Category: DIGITAL-MEDIA
Preview:          SENIOR DIGITAL MARKETING ANALYST       Summary    Highly analytical and process-oriented data analyst with in-depth knowledge of
marketing p
------------------------------------------------------------
Final Score: 0.444
Category: AUTOMOBILE
Preview:          DATA ANALYST       Professional Summary    Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Gr
------------------------------------------------------------
Final Score: 0.428
Category: BUSINESS-DEVELOPMENT
Preview:          BUSINESS DEVELOPMENT ANALYST       Summary     Extensive Analyst experience with emphasis on Business Development and Data Analytic    Ambiti
------------------------------------------------------------
Final Score: 0.428
Category: BUSINESS-DEVELOPMENT
Preview:          BUSINESS DEVELOPMENT EXECUTIVE       Summary    Process oriented Data Analyst and Delivery Lead with 5+ years proven track record of analyzin
------------------------------------------------------------
Final Score: 0.421
Category: SALES
Preview:          SALES COORDINATOR       Summary    Current MS of Data Analytics graduate student with exposure to data analysis and modeling
          skills
------------------------------------------------------------

[(1303, 0.45750216942207483),
 (1339, 0.4439589808968937),
 (563, 0.4277991668850768),
 (662, 0.4277844195272409),
 (1040, 0.4210761378793155),
 (315, 0.41345980331009513),
 (2171, 0.40213587330836875),
 (2242, 0.40056445645351035),
 (717, 0.3993259261636173),
 (331, 0.39898379550260654),
 (1766, 0.39502837167066684),
 (583, 0.39182002170413155),
 (1899, 0.3869487528707467),
 (2221, 0.38249549912471403),
 (1207, 0.37710704967087394),
 (2385, 0.37508096858566886),
 (753, 0.3717155938055001),
 (1724, 0.370364356508442),
 (1172, 0.3698038582708322),
 (1251, 0.3694337968732797),
 (17, 0.36705687747282145),
 (1532, 0.36464896248836143),
 (1153, 0.36263837861079795),
 (1271, 0.3582416062261544),
 (2395, 0.35238843010921106),
 (438, 0.3515746902017033),
 (2466, 0.3437443022634469),
 (64, 0.34103885935802086),
 (1282, 0.3335062031652413),
 (1714, 0.3201495836762821),
 (92, 0.3199715976621591)]

In [281]:
#testing multiple roles

rank_candidates(jd_index=4)  # Data Scientist
rank_candidates(jd_index=2)  # HR Analyst

Top 5 candidates for role: Data Scientist

Final Score: 0.486
Category: ENGINEERING
Preview:          ENGINEERING AND QUALITY TECHNICIAN       Career Overview    A highly experienced skilled graduate with Analytics degree with a very good expe
------------------------------------------------------------
Final Score: 0.446
Category: AUTOMOBILE
Preview:         Highlights          Prog. Languages:          C (5+ yrs), Python (3+ yrs), Java (3+ yrs), MATLAB (Simulink) (5+ yrs), R (2 yrs), Processing (2
------------------------------------------------------------
Final Score: 0.426
Category: AUTOMOBILE
Preview:          DATA ANALYST       Professional Summary    Industrial and Systems Engineering graduate, certified Base SAS Programmer and a Lean Six Sigma Gr
------------------------------------------------------------
Final Score: 0.421
Category: CONSULTANT
Preview:        Pavithra  Shetty           Summary     Customer-oriented Principal Consultant knowledgeable about developing and implementing successful busine
------------------------------------------------------------
Final Score: 0.416
Category: ENGINEERING
Preview:          ENGINEERING INTERN         Skills          C++, Python, MATLAB, Git, Bash, R, SQL (basic). Experienced in Linux/Unix and using high performan
------------------------------------------------------------

Top 5 candidates for role: HR Analyst

Final Score: 0.47
Category: HR
Preview:          HR CONSULTING       Summary    7+ years of Experience as a HR Partner with experience in all the facets of the Human Resource Function. Exten
------------------------------------------------------------
Final Score: 0.459
Category: HR
Preview:          FIELD HR ASSOCIATE           Summary    Reliable HR Field Associate with a Master's of science in Human Resource management emphasis as a Gen
------------------------------------------------------------
Final Score: 0.456
Category: CONSULTANT
Preview:          CONSULTANT       Career Focus     Business Professional acutely focused on customer service and network building. Promptly develops vital rel
------------------------------------------------------------
Final Score: 0.454
Category: HR
Preview:          HR MANAGER         Skill Highlights           HR SKILLS  HR Department Startup  Three New Organization Startups  Employment Law  FMLA/ADA/EEO
------------------------------------------------------------
Final Score: 0.454
Category: HR
Preview:          ASSISTANT MANAGER - HR            www.linkedin.com/in/sumankumari725b9236         Professional Summary     Looking for a challenging position
------------------------------------------------------------

[(65, 0.4700235287348429),
 (81, 0.4590316216150919),
 (1197, 0.45605635378095843),
 (4, 0.4544990340868632),
 (78, 0.4543586889902751),
 (1170, 0.45206485324435763),
 (2227, 0.4518206755320231),
 (77, 0.4505511085192362),
 (1583, 0.45050526724921336),
 (17, 0.4489155213038126),
 (19, 0.4486659632788764),
 (87, 0.44838709036509194),
 (1340, 0.4463754455248514),
 (2422, 0.4442096564504835),
 (85, 0.43539928065405953),
 (1344, 0.43492954307132303),
 (42, 0.43454912238650856),
 (22, 0.4332083331214057),
 (71, 0.43274927006827457),
 (35, 0.4322042332755195),
 (106, 0.43165658050113254),
 (8, 0.4314747439490424),
 (92, 0.4314568307664659),
 (80, 0.43048103385501435),
 (2124, 0.4291480355792575),
 (40, 0.42906001673804395),
 (61, 0.4281329260932075),
 (5, 0.4280053536097208),
 (31, 0.42757288085089795),
 (10, 0.4273260407977634),
 (723, 0.42566672431098096),
 (54, 0.42559571133719554),
 (773, 0.42543270455466375),
 (1118, 0.42527041435241697),
 (62, 0.4242417573928833),
 (11, 0.4237280236350166),
 (94, 0.4235949794451396),
 (9, 0.4235238605075412),
 (41, 0.42162564330630836),
 (27, 0.42151253223419194),
 (13, 0.4209476643138462),
 (679, 0.42061198287540014),
 (88, 0.42045755253897776),
 (1641, 0.41920266681247287),
 (108, 0.41871887842814126),
 (2229, 0.41849106417761905),
 (52, 0.4179068141513401),
 (1215, 0.416226577758789),
 (253, 0.41562109523349344),
 (686, 0.4151949935489231),
 (2115, 0.4150616513358222),
 (770, 0.4144273810916477),
 (89, 0.4138027535544502),
 (23, 0.4135052137904697),
 (98, 0.41341109275817867),
 (2474, 0.4113743835025364),
 (1834, 0.4109853201442295),
 (1001, 0.4102557169066535),
 (33, 0.41021965079837375),
 (75, 0.41003035306930546),
 (471, 0.4088783436351352),
 (830, 0.40864079528384745),
 (2330, 0.4078310595618354),
 (968, 0.4077001015345255),
 (2106, 0.4070829153060913),
 (541, 0.40646132893032494),
 (1625, 0.4062452846103245),
 (7, 0.4062279224395752),
 (16, 0.4059983200497097),
 (1802, 0.4057887964778476),
 (538, 0.4052355527877808),
 (1589, 0.4050836907492744),
 (21, 0.4043829560279846),
 (91, 0.4042976180712382),
 (749, 0.40382346312205),
 (47, 0.4038071513175965),
 (67, 0.4034030675888062),
 (24, 0.4033677577972412),
 (1216, 0.40159733957714505),
 (694, 0.40159117513232767),
 (570, 0.4012739658355713),
 (1750, 0.40041382312774654),
 (583, 0.40026551352606876),
 (105, 0.40019155078464086),
 (18, 0.40012537903255885),
 (639, 0.40008977651596067),
 (1580, 0.3999656372600132),
 (1882, 0.39985606670379636),
 (1893, 0.39967209100723267),
 (1865, 0.3991480946540833),
 (617, 0.39886677265167236),
 (1144, 0.39875094890594487),
 (14, 0.3987212419509888),
 (1870, 0.39789341025882297),
 (230, 0.39767720699310305),
 (2221, 0.3964904361300998),
 (1326, 0.39501566224628026),
 (280, 0.39429433345794673),
 (1202, 0.3941770142979092),
 (68, 0.3940775871276856),
 (1240, 0.3936737524138557),
 (753, 0.3935334497027927),
 (1124, 0.3931014829211765),
 (2184, 0.393082857131958),
 (1151, 0.39305703639984135),
 (51, 0.39283803568945996),
 (34, 0.3927858538097806),
 (1714, 0.3927690903345744),
 (512, 0.3925717221366035),
 (223, 0.3921171479754978),
 (536, 0.39179471068912086),
 (758, 0.3915961742401123),
 (1673, 0.3915804333157009),
 (25, 0.3915434188312954),
 (1167, 0.391150438785553),
 (1709, 0.3906091213226318),
 (706, 0.3903737412558662),
 (306, 0.3901405639118618),
 (1164, 0.389807915687561),
 (908, 0.389743709564209),
 (1899, 0.3896261745029026),
 (1191, 0.38919417858123784),
 (2429, 0.3891199827194214),
 (1537, 0.3890027946896023),
 (1872, 0.38893907599978983),
 (1911, 0.3884520477718777),
 (53, 0.3880945377879672),
 (1803, 0.38807374238967896),
 (1535, 0.3880704402923584),
 (43, 0.38784323268466525),
 (26, 0.38714388608932493),
 (2337, 0.3868543386459351),
 (64, 0.38684861660003667),
 (675, 0.3866185665130615),
 (1538, 0.38655078411102295),
 (1175, 0.38644748263888884),
 (790, 0.3857793039745755),
 (1837, 0.38544385433197026),
 (2125, 0.38519019418292577),
 (1555, 0.38506171173519554),
 (1477, 0.3844449917475382),
 (700, 0.3839719149801466),
 (957, 0.3838726811938815),
 (1211, 0.38385508722729156),
 (2363, 0.38371363083521526),
 (1282, 0.3836178461710612),
 (1229, 0.3835086517863804),
 (983, 0.38348493046230736),
 (589, 0.38343114323086214),
 (1991, 0.3833761029773288),
 (1513, 0.38335583209991453),
 (348, 0.3833186202579074),
 (1178, 0.383055673705207),
 (32, 0.38268883228302),
 (565, 0.38228969573974614),
 (1462, 0.3822890520095825),
 (845, 0.3820456451839871),
 (1977, 0.3818907976150513),
 (2203, 0.38168820010291205),
 (498, 0.3815991229481167),
 (2466, 0.38154205613666115),
 (97, 0.38122537136077883),
 (2077, 0.3810863203472561),
 (2, 0.38077054023742674),
 (1122, 0.38023049831390376),
 (1507, 0.380201256275177),
 (15, 0.37953787512249415),
 (250, 0.37936969333224824),
 (2007, 0.3790231704711914),
 (104, 0.37888252205318873),
 (235, 0.3788546204566956),
 (2130, 0.3785241232977973),
 (109, 0.37824045419693),
 (69, 0.37819985813564727),
 (1141, 0.37816504637400306),
 (290, 0.37763614124721956),
 (815, 0.37733304368125065),
 (1827, 0.37723776764339867),
 (2384, 0.3772035121917725),
 (1483, 0.3771245241165161),
 (55, 0.3766038603252835),
 (1634, 0.37657671504550505),
 (44, 0.37584745354122584),
 (1631, 0.3752755814128452),
 (1817, 0.37520332336425777),
 (293, 0.37508559226989746),
 (1725, 0.3745775699615479),
 (2168, 0.37428107791476783),
 (74, 0.3741121835178799),
 (1, 0.37397988372378876),
 (1336, 0.3739763975143433),
 (2334, 0.37381744384765625),
 (881, 0.3737703270382351),
 (93, 0.3736954636043972),
 (1356, 0.37363440990447994),
 (988, 0.3727552705340915),
 (2374, 0.3727315889464484),
 (1955, 0.3722862839698792),
 (1702, 0.37227705187267723),
 (1841, 0.37222530841827395),
 (1578, 0.3720767259597778),
 (1737, 0.371707820892334),
 (2370, 0.37169361114501953),
 (1861, 0.3715737104415894),
 (1894, 0.3715210504002041),
 (307, 0.3713390111923218),
 (79, 0.37064270443386504),
 (2373, 0.3699369192123413),
 (1193, 0.3698073625564575),
 (2003, 0.3696312639448378),
 (1785, 0.3695217318005032),
 (912, 0.3694276677237617),
 (2170, 0.36908166408538823),
 (678, 0.36907551288604734),
 (483, 0.3690317749977112),
 (1585, 0.3689636654324002),
 (2413, 0.3682488626903958),
 (823, 0.36807740264468725),
 (733, 0.3674580163425869),
 (1606, 0.3663736157947116),
 (2245, 0.36622650093502473),
 (668, 0.36583002143436005),
 (977, 0.36579483217663233),
 (485, 0.36564661926693387),
 (781, 0.3655411058002048),
 (1545, 0.3655149406856961),
 (148, 0.365466754966312),
 (2108, 0.36545266575283475),
 (2119, 0.3651716417736477),
 (1484, 0.3650585836834378),
 (1862, 0.36501364178127715),
 (1460, 0.3650132722324795),
 (101, 0.3649211406707764),
 (272, 0.3646664328045315),
 (1672, 0.3645103640026517),
 (281, 0.3644465631908841),
 (1060, 0.36439433627658424),
 (588, 0.3643920278549195),
 (1532, 0.3641171150737339),
 (2222, 0.364074522919125),
 (229, 0.36404814190334744),
 (1879, 0.3639275378651089),
 (1629, 0.3638433390193515),
 (2068, 0.36377398967742924),
 (591, 0.3635959572262234),
 (946, 0.36358354091644285),
 (549, 0.36327116489410405),
 (2180, 0.36316479974322846),
 (246, 0.36288542747497554),
 (708, 0.3626940197414822),
 (427, 0.36204271316528325),
 (598, 0.3619370698928833),
 (278, 0.36164702177047725),
 (1238, 0.3616201625929939),
 (1888, 0.3615384048885769),
 (1224, 0.36150196128421364),
 (1172, 0.36138615078396263),
 (925, 0.361202597618103),
 (1452, 0.36115813917583894),
 (574, 0.36115227275424533),
 (1531, 0.3607392549514771),
 (2386, 0.36073218584060673),
 (2107, 0.36056109666824343),
 (525, 0.3605325169033474),
 (1084, 0.3604988574981689),
 (575, 0.3604698830180698),
 (1165, 0.3603259987301296),
 (46, 0.360073369079166),
 (1577, 0.3597732014126248),
 (1307, 0.3596117668681674),
 (1210, 0.35942742294735375),
 (1985, 0.3592385954327053),
 (1582, 0.35912821292877195),
 (1264, 0.358833909034729),
 (2369, 0.358821964263916),
 (2059, 0.35876514381832547),
 (1902, 0.3586748904652065),
 (1741, 0.3582959360546536),
 (1946, 0.3581344193882412),
 (1952, 0.3580022282070584),
 (2359, 0.35777355300055613),
 (1916, 0.3571778893470764),
 (1568, 0.35700690216488307),
 (555, 0.356971902317471),
 (95, 0.35673282146453855),
 (1845, 0.3566358327865601),
 (981, 0.35642753309673736),
 (1868, 0.3561468362808228),
 (869, 0.356146228313446),
 (1579, 0.3557654857635498),
 (1270, 0.3551756448215908),
 (0, 0.35505806207656865),
 (1522, 0.35497738785213895),
 (1864, 0.3547959751553006),
 (529, 0.35445616245269773),
 (1797, 0.35436262554592557),
 (1856, 0.35433937973446317),
 (2233, 0.35404872364468043),
 (748, 0.3537756866878933),
 (1648, 0.35370983944998846),
 (2089, 0.3533696360058255),
 (1550, 0.3532918400234646),
 (1912, 0.3527552127838135),
 (602, 0.3526024527019924),
 (1222, 0.3525696516036987),
 (2308, 0.35254606008529665),
 (2390, 0.35242359638214116),
 (1213, 0.3522364801830715),
 (521, 0.3518905109829372),
 (2174, 0.3518757290310329),
 (1312, 0.351838755607605),
 (697, 0.3500052160686916),
 (1481, 0.34958453840679593),
 (1787, 0.34907820887035795),
 (1496, 0.34894790119595),
 (2444, 0.3486561960644192),
 (2483, 0.3486561722225613),
 (797, 0.34857630199856227),
 (1818, 0.34850685066647),
 (1959, 0.34831194877624516),
 (1835, 0.3480019516415066),
 (1647, 0.3478578686714172),
 (1546, 0.34769713348812525),
 (326, 0.3469781822628445),
 (1539, 0.34689194626278347),
 (1825, 0.34678739971584743),
 (460, 0.34659466743469236),
 (1286, 0.34634794659084744),
 (1901, 0.34596321052975126),
 (1608, 0.345930380291409),
 (626, 0.3457162804073758),
 (969, 0.34530790381961396),
 (1594, 0.3451397895812989),
 (671, 0.3450911945766873),
 (941, 0.3448747396469116),
 (2411, 0.344617223739624),
 (1143, 0.3446133083767361),
 (128, 0.34442743725246855),
 (2410, 0.34441663026809693),
 (949, 0.34354286723666727),
 (784, 0.34345509476131864),
 (2261, 0.34336738586425786),
 (1093, 0.34298891491360134),
 (2426, 0.3429379410213894),
 (2248, 0.3427805370754666),
 (319, 0.34254482454723784),
 (1140, 0.34240825838512845),
 (1850, 0.3422930068439908),
 (321, 0.3414474195904202),
 (239, 0.34121272034115263),
 (961, 0.34110795921749537),
 (1521, 0.34086090988583034),
 (1676, 0.3405811548233032),
 (1691, 0.3404861397213406),
 (1514, 0.3403831786579556),
 (1492, 0.34036407470703123),
 (573, 0.34027985996670196),
 (2470, 0.340228099293179),
 (414, 0.3398387140697903),
 (2083, 0.33952922821044923),
 (993, 0.33931820392608647),
 (1887, 0.3390835232204861),
 (1979, 0.33903614944881866),
 (786, 0.33878531455993655),
 (1730, 0.3385402149624295),
 (1658, 0.33853018283843994),
 (228, 0.33813316822052003),
 (2235, 0.337825083732605),
 (2344, 0.33768112659454347),
 (2172, 0.33765721850925023),
 (1506, 0.3375405020183987),
 (752, 0.3373701161808438),
 (2400, 0.3370921916431851),
 (926, 0.33692528671688504),
 (1996, 0.3368281549877591),
 (2161, 0.3365536398357815),
 (1145, 0.33550620741314363),
 (1966, 0.3354551023907132),
 (1942, 0.3354259610176087),
 (1327, 0.3353892511791653),
 (1301, 0.3353874354892307),
 (642, 0.3351731008953518),
 (2153, 0.3351246452331543),
 (1467, 0.33483095169067384),
 (1779, 0.33470715946621366),
 (1341, 0.3346452779240079),
 (2223, 0.3345110363430447),
 (154, 0.3344405836529202),
 (49, 0.3335399670071072),
 (301, 0.3333522266811795),
 (1784, 0.3328589200973511),
 (2207, 0.3326179093784756),
 (2185, 0.3325947284698486),
 (2188, 0.33250704473919335),
 (2193, 0.3323982066578335),
 (1075, 0.33236782020992706),
 (532, 0.33206428951687283),
 (504, 0.3318755335277981),
 (494, 0.3308710217475891),
 (731, 0.3308133429951138),
 (960, 0.33062673277325105),
 (962, 0.33029305934906006),
 (2162, 0.33022534184985697),
 (2351, 0.33014019197887845),
 (2468, 0.32969294256634185),
 (595, 0.32955696052975125),
 (2430, 0.32819082736968996),
 (2019, 0.3257073468632168),
 (2156, 0.32541215419769287),
 (456, 0.32494037151336674),
 (383, 0.3247765011257595),
 (1933, 0.3235485977596707),
 (1384, 0.3235221385955811),
 (354, 0.3230384058422513),
 (873, 0.32267763084835477),
 (1566, 0.32223572201199),
 (839, 0.32205129861831666),
 (2209, 0.32157780594295926),
 (1542, 0.3215142488479614),
 (1296, 0.32135406202740135),
 (2062, 0.32111656665802),
 (2134, 0.3201768106884426),
 (755, 0.31979369587368434),
 (1964, 0.31944503254360623),
 (1463, 0.31917750305599635),
 (291, 0.3186410493320889),
 (2460, 0.31803371376461453),
 (1088, 0.31778341001934474),
 (201, 0.3177195019192166),
 (821, 0.31659427351421776),
 (123, 0.31658829384379916),
 (1056, 0.31649162239498563),
 (1776, 0.3161108560032315),
 (827, 0.315821976131863),
 (2047, 0.31539149284362794),
 (1006, 0.31481452650494046),
 (1598, 0.31424752473831175),
 (684, 0.3138836205005646),
 (2109, 0.31349586910671656),
 (898, 0.31266351408428616),
 (2278, 0.31261072158813474),
 (2461, 0.3113602203792996),
 (2355, 0.31115683979458275),
 (2177, 0.3109575748443604),
 (2178, 0.30974804759025576),
 (1685, 0.3095308966106839),
 (131, 0.30944395131534996),
 (1778, 0.3093583590454525),
 (1315, 0.3093350595898099),
 (2065, 0.3092184490627713),
 (940, 0.3090213656425476),
 (2024, 0.30891575045055814),
 (2038, 0.30885179572635224),
 (1428, 0.308160048060947),
 (431, 0.30739739603466454),
 (1402, 0.30686633057064483),
 (2072, 0.30680749482578706),
 (1288, 0.3060581207275391),
 (606, 0.30419264501995513),
 (1162, 0.3040220422214932),
 (1085, 0.3023705667919583),
 (1453, 0.30164594120449495),
 (1397, 0.29801130228572426),
 (896, 0.2977665669388241),
 (1250, 0.29752662844128075),
 (802, 0.2914482898182339),
 (2482, 0.28974306053585475),
 (980, 0.28826934761471223),
 (2249, 0.28818162149853177),
 (882, 0.2873097605175442),
 (1430, 0.2861282527446747),
 (2091, 0.2788014239735074),
 (1674, 0.27819665140575833),
 (1451, 0.2682609207100338),
 (469, 0.2635374969906277),
 (2080, 0.26178271598286096),
 (1431, 0.2596881604856915),
 (2157, 0.2592622823185391)]

In [365]:
!pip install --upgrade transformers accelerate

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in c:\users\bomma\appdata\roaming\python\python312\site-packages (5.5.4)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in c:\users\bomma\appdata\roaming\python\python312\site-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in c:\programdata\anaconda3\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\programdata\anaconda3\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from accelerate) (5.9.0)
Requirement already satisfied: torch>=2.0.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from accelerate) (2.10.0)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.27.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from torch>=2.0.0->accelerate) (75.1.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\programdata\anaconda3\lib\site-packages (from typer->transformers) (13.7.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\bomma\appdata\roaming\python\python312\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.2.0)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.2)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.15.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.3)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.0)
Downloading transformers-5.7.0-py3-none-any.whl (10.5 MB)
   ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.5 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/10.5 MB 6.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/10.5 MB 5.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/10.5 MB 5.7 MB/s eta 0:00:02
   ---------------------- ----------------- 5.8/10.5 MB 5.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.9/10.5 MB 6.5 MB/s eta 0:00:01
   -------------------------------------- - 10.0/10.5 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 10.5/10.5 MB 6.7 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.5.4
    Uninstalling transformers-5.5.4:
      Successfully uninstalled transformers-5.5.4
Successfully installed transformers-5.7.0

  WARNING: The script transformers.exe is installed in 'C:\Users\Bomma\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [443]:
#loading the model

from transformers import pipeline

generator = pipeline("text2text-generation", model="google/flan-t5-base")

KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [445]:
#get top candidate
results = rank_candidates(jd_index=0)

if len(results) == 0:
    print("No candidates found")
else:
    top_idx = results[0][0]
    top_score = results[0][1]

In [447]:
#clean context
def clean_output(text):
    # Remove everything before actual explanation
    lines = text.split("\n")
    
    for line in lines:
        if len(line.strip()) > 20 and "candidate" in line.lower():
            return line.strip()
    
    # fallback
    return lines[-1].strip()

In [449]:
#strong prompt

def build_prompt(context):
    return f"""
Explain in one sentence why this candidate is suitable for a Data Analyst role.

{context}
"""

In [451]:
#llm function
def ask_llm(context):
    prompt = build_prompt(context)
    
    response = generator(
        prompt,
        max_new_tokens=30,   # 🔥 reduce further
        do_sample=False
    )
    
    return response[0]['generated_text'].strip()

In [465]:
def generate_explanation(idx, role):
    skills = df.iloc[idx]['Keywords']
    
    # Remove duplicates while preserving order
    unique_skills = list(dict.fromkeys(skills))
    
    if role == "Data Analyst":
        required = ["python", "sql", "excel", "analysis", "data"]
        matched = [s for s in unique_skills if s in required]
        
        # Take only unique meaningful skills
        matched = list(dict.fromkeys(matched))[:3]
        
        return f"Candidate has strong skills in {', '.join(matched)} which are essential for Data Analyst role."
    
    elif role == "HR Analyst":
        required = ["hr", "recruitment", "employee", "management"]
        matched = [s for s in unique_skills if s in required]
        matched = list(dict.fromkeys(matched))[:3]
        
        return f"Candidate has relevant HR experience and skills in {', '.join(matched)}."
    
    else:
        return "Candidate has relevant experience and skills matching the job requirements."

In [467]:
#final execution
results = rank_candidates(jd_index=0)

if len(results) > 0:
    top_idx = results[0][0]
    top_score = results[0][1]
    
    role = jd_df.iloc[0]['role']
    
    explanation = generate_explanation(top_idx, role)
    
    print("Best Candidate ID:", top_idx)
    print("Score:", round(top_score,2))
    print("Explanation:", explanation)

else:
    print("No candidates found")

Best Candidate ID: 1303
Score: 0.46
Explanation: Candidate has strong skills in analysis, excel, sql which are essential for Data Analyst role.